import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import { getFooterMenus } from '@/lib/sanity.services'
import { ThemeProvider } from 'next-themes'
import NextTopLoader from 'nextjs-toploader';
import SessionProviderComp from '@/components/nextauth/SessionProvider'
import { getNavLinks } from '@/lib/sanity.services'

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Homely - A Real Estate Framer Template',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode
  session: any
}>) {
  const navLinks = await getNavLinks()
  const footerMenus = await getFooterMenus()

  return (
    <html lang='en'>
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#2596be" />
        <SessionProviderComp session={session}>
          <ThemeProvider
            attribute='class'
            enableSystem={true}
            defaultTheme='light'>
            <Header navLinks={navLinks} />
            {children}
            <Footer footerMenus={footerMenus} />
          </ThemeProvider>
        </SessionProviderComp>
      </body>
    </html>
  )
}
